In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
num_episodes = 10000 #total number of episodes we want our agent to play during the training
max_steps_per_episode = 100 #max number of steps that our agent can take during each episode

learning_rate = 0.1 
discount_rate = 0.99

exploration_rate =1 
max_exploration_rate =1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001 #rate to lower exploration rate

In [13]:
rewards_all_episodes = []

for episode in range(num_episodes):
  state = env.reset()
  done = False
  rewards_current_episode=0

  for step in range (max_steps_per_episode):
    exploration_rate_threshold = random.uniform(0,1)

    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:]) #find the action that has the highest q_value in the q_table for the given state
    else: 
      action = env.action_space.sample()

    new_state, reward, done, info = env.step(action)

    q_table[state, action] = q_table[state,action]*(1-learning_rate)+learning_rate*(reward+discount_rate*np.max(q_table[new_state, :]))
    # new q_value is the weighted sum of the old and the learned value

    state = new_state
    rewards_current_episode += reward

    if done == True:
      break
  #exp rate decay
  exploration_rate= min_exploration_rate + (max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)

  rewards_all_episodes.append(rewards_current_episode)

rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000

print("@@@@@@@-Averaged Reward per Thousand Episodes-@@@@@@@@ \n")
for r in rewards_per_thousand_episodes:
  print(count, ":", str(sum(r/1000)))
  count += 1000

print("\n\n @@@@@@-Q Table-@@@@@@")
print(q_table)

@@@@@@@-Averaged Reward per Thousand Episodes-@@@@@@@@ 

1000 : 0.05000000000000004
2000 : 0.20800000000000016
3000 : 0.3970000000000003
4000 : 0.5370000000000004
5000 : 0.6190000000000004
6000 : 0.6930000000000005
7000 : 0.6590000000000005
8000 : 0.6630000000000005
9000 : 0.6650000000000005
10000 : 0.6910000000000005


 @@@@@@-Q Table-@@@@@@
[[0.56244351 0.50374078 0.53593381 0.51974024]
 [0.3419895  0.27539613 0.32688508 0.5168152 ]
 [0.40867479 0.42164054 0.40095301 0.47682106]
 [0.34389555 0.30915763 0.34316964 0.45863236]
 [0.57291142 0.36507708 0.37252351 0.30702495]
 [0.         0.         0.         0.        ]
 [0.33159692 0.11499452 0.18440949 0.16258189]
 [0.         0.         0.         0.        ]
 [0.35483417 0.32312083 0.34693794 0.61286164]
 [0.5407543  0.69400806 0.38552982 0.38314863]
 [0.62403261 0.43476382 0.19706061 0.28623298]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.35866958 0.5366748  0.80700541 0.4420768

In [16]:
for episode in range(3):
  state = env.reset()
  done = False
  print("@@@-Episode--", episode+1, "--@@@\n\n")
  time.sleep(1)

  for step in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)
  
    action = np.argmax(q_table[state, :])
    new_state, reward, done, info = env.step(action)
  
    if done:
      clear_output(wait=True)
      env.render()
      if reward ==1:
        print("Goal Reached")
        time.sleep(3)
      else:
        print("You are down the hole...")
        time.sleep(3)
  
      clear_output(wait=True)
      break
  
    state=new_state

env.close()



  (Left)
SFFF
FHFH
FFFH
HFFG
You are down the hole...
